In [1]:
import pandas as pd
import requests, io

In [2]:
api_url = "https://data.moenv.gov.tw/api/v2/aqx_p_02?api_key=af57253c-e838-46da-a1f5-12b43afd75f3&limit=1000&sort=datacreationdate%20desc&format=CSV"

In [26]:
api_json = "https://data.moenv.gov.tw/api/v2/aqx_p_02?api_key=846e44e1-8cc5-4893-ad87-c79d2d383706&limit=1000&sort=datacreationdate%20desc&format=JSON"

## 避開SSL認證

In [27]:
resp = requests.get(api_url, verify=False)
print(resp)
df = pd.read_csv(io.StringIO(resp.text))
df

<Response [200]>

c:\Users\USER\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.moenv.gov.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Empty DataFrame
Columns: [因受限於資源分配，每日呼叫API的次數不可大於5000次。]
Index: []

In [28]:
df = pd.read_json(api_json)
df

     site county  pm25  datacreationdate itemunit
0      林森    臺南市    18  2026-04-19 13:00    μg/m3
1      員林    彰化縣    20  2026-04-19 13:00    μg/m3
2    臺灣大道    臺中市    13  2026-04-19 13:00    μg/m3
3      大城    彰化縣    19  2026-04-19 13:00    μg/m3
4     富貴角    新北市     8  2026-04-19 13:00    μg/m3
..    ...    ...   ...               ...      ...
995    線西    彰化縣    24  2026-04-19 01:00    μg/m3
996    彰化    彰化縣    24  2026-04-19 01:00    μg/m3
997    西屯    臺中市    24  2026-04-19 01:00    μg/m3
998    忠明    臺中市    23  2026-04-19 01:00    μg/m3
999    大里    臺中市    30  2026-04-19 01:00    μg/m3

[1000 rows x 5 columns]

In [4]:
df = pd.read_csv(api_url)
df

Empty DataFrame
Columns: [因受限於資源分配，每日呼叫API的次數不可大於5000次。]
Index: []

## 清理資料、移除空值、移除重複

In [29]:
## 查看資料結構→ 空值、筆數、型態
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   site              1000 non-null   str
 1   county            1000 non-null   str
 2   pm25              1000 non-null   int64
 3   datacreationdate  1000 non-null   str
 4   itemunit          1000 non-null   str
dtypes: int64(1), str(4)
memory usage: 39.2 KB

In [30]:
df.describe()

              pm25
count  1000.000000
mean     21.721000
std       8.429129
min       0.000000
25%      15.000000
50%      21.000000
75%      28.000000
max      46.000000

In [31]:
# 查看重複值
# df.duplicated()
# df[df.duplicated(subset=["site", "datacreationdate"])]

# df.drop_duplicates()
df.drop_duplicates(subset=["site", "datacreationdate"])

     site county  pm25  datacreationdate itemunit
0      林森    臺南市    18  2026-04-19 13:00    μg/m3
1      員林    彰化縣    20  2026-04-19 13:00    μg/m3
2    臺灣大道    臺中市    13  2026-04-19 13:00    μg/m3
3      大城    彰化縣    19  2026-04-19 13:00    μg/m3
4     富貴角    新北市     8  2026-04-19 13:00    μg/m3
..    ...    ...   ...               ...      ...
995    線西    彰化縣    24  2026-04-19 01:00    μg/m3
996    彰化    彰化縣    24  2026-04-19 01:00    μg/m3
997    西屯    臺中市    24  2026-04-19 01:00    μg/m3
998    忠明    臺中市    23  2026-04-19 01:00    μg/m3
999    大里    臺中市    30  2026-04-19 01:00    μg/m3

[1000 rows x 5 columns]

### .dropna() 移除空值

In [8]:
df.drop_duplicates(subset=["site", "datacreationdate"]).dropna()

Empty DataFrame
Columns: [因受限於資源分配，每日呼叫API的次數不可大於5000次。]
Index: []

In [32]:
df1 = df.drop_duplicates(subset=["site", "datacreationdate"]).dropna()
df1

     site county  pm25  datacreationdate itemunit
0      林森    臺南市    18  2026-04-19 13:00    μg/m3
1      員林    彰化縣    20  2026-04-19 13:00    μg/m3
2    臺灣大道    臺中市    13  2026-04-19 13:00    μg/m3
3      大城    彰化縣    19  2026-04-19 13:00    μg/m3
4     富貴角    新北市     8  2026-04-19 13:00    μg/m3
..    ...    ...   ...               ...      ...
995    線西    彰化縣    24  2026-04-19 01:00    μg/m3
996    彰化    彰化縣    24  2026-04-19 01:00    μg/m3
997    西屯    臺中市    24  2026-04-19 01:00    μg/m3
998    忠明    臺中市    23  2026-04-19 01:00    μg/m3
999    大里    臺中市    30  2026-04-19 01:00    μg/m3

[1000 rows x 5 columns]

## sqlite 建立資料庫
- unique(site, datacreationdate)
    - 插入資料唯一的約束
- 整數寫法→ integer
    - 不能寫 int
- autoincrement
    - 不是寫 auto_increment

In [10]:
import sqlite3

In [11]:
sqlstr = '''
create table if not exists data(
id integer primary key autoincrement,
site text,
county text,
pm25 integer,
datacreationdate text,
itemunit text,
unique(site, datacreationdate)
)
'''

In [12]:
conn = sqlite3.connect("pm25.db")
cursor = conn.cursor()
conn, cursor

(<sqlite3.Connection at 0x22936d6c040>, <sqlite3.Cursor at 0x22936d54d40>)

In [13]:
cursor.execute(sqlstr)
conn.commit()

### 插入資料
- or ignore
    - 忽略重複資料

In [33]:
sqlstr = "insert or ignore into data (site,county,pm25,datacreationdate,itemunit)\
    values(?, ?, ?, ?, ?)"

In [34]:
# df1.values
df1.values.tolist()

[['林森', '臺南市', 18, '2026-04-19 13:00', 'μg/m3'],
 ['員林', '彰化縣', 20, '2026-04-19 13:00', 'μg/m3'],
 ['臺灣大道', '臺中市', 13, '2026-04-19 13:00', 'μg/m3'],
 ['大城', '彰化縣', 19, '2026-04-19 13:00', 'μg/m3'],
 ['富貴角', '新北市', 8, '2026-04-19 13:00', 'μg/m3'],
 ['麥寮', '雲林縣', 12, '2026-04-19 13:00', 'μg/m3'],
 ['關山', '臺東縣', 13, '2026-04-19 13:00', 'μg/m3'],
 ['馬公', '澎湖縣', 10, '2026-04-19 13:00', 'μg/m3'],
 ['金門', '金門縣', 23, '2026-04-19 13:00', 'μg/m3'],
 ['馬祖', '連江縣', 26, '2026-04-19 13:00', 'μg/m3'],
 ['埔里', '南投縣', 19, '2026-04-19 13:00', 'μg/m3'],
 ['復興', '高雄市', 21, '2026-04-19 13:00', 'μg/m3'],
 ['永和', '新北市', 14, '2026-04-19 13:00', 'μg/m3'],
 ['竹山', '南投縣', 26, '2026-04-19 13:00', 'μg/m3'],
 ['中壢', '桃園市', 15, '2026-04-19 13:00', 'μg/m3'],
 ['三重', '新北市', 13, '2026-04-19 13:00', 'μg/m3'],
 ['冬山', '宜蘭縣', 11, '2026-04-19 13:00', 'μg/m3'],
 ['宜蘭', '宜蘭縣', 13, '2026-04-19 13:00', 'μg/m3'],
 ['陽明', '臺北市', 17, '2026-04-19 13:00', 'μg/m3'],
 ['花蓮', '花蓮縣', 15, '2026-04-19 13:00', 'μg/m3'],
 ['臺東', '臺東縣', 17, '2026-04-19 13:00', 'μg/m3'],
 ['恆春', '屏東縣', 16, '2026-04-19 13:00', 'μg/m3'],
 ['潮州', '屏東縣', 32, '2026-04-19 13:00', 'μg/m3'],
 ['屏東', '屏東縣', 20, '2026-04-19 13:00', 'μg/m3'],
 ['小港', '高雄市', 26, '2026-04-19 13:00', 'μg/m3'],
 ['前鎮', '高雄市', 21, '2026-04-19 13:00', 'μg/m3'],
 ['前金', '高雄市', 22, '2026-04-19 13:00', 'μg/m3'],
 ['左營', '高雄市', 21, '2026-04-19 13:00', 'μg/m3'],
 ['楠梓', '高雄市', 23, '2026-04-19 13:00', 'μg/m3'],
 ['林園', '高雄市', 24, '2026-04-19 13:00', 'μg/m3'],
 ['大寮', '高雄市', 31, '2026-04-19 13:00', 'μg/m3'],
 ['鳳山', '高雄市', 24, '2026-04-19 13:00', 'μg/m3'],
 ['仁武', '高雄市', 22, '2026-04-19 13:00', 'μg/m3'],
 ['橋頭', '高雄市', 21, '2026-04-19 13:00', 'μg/m3'],
 ['美濃', '高雄市', 16, '2026-04-19 13:00', 'μg/m3'],
 ['臺南', '臺南市', 19, '2026-04-19 13:00', 'μg/m3'],
 ['安南', '臺南市', 25, '2026-04-19 13:00', 'μg/m3'],
 ['善化', '臺南市', 18, '2026-04-19 13:00', 'μg/m3'],
 ['新營', '臺南市', 21, '2026-04-19 13:00', 'μg/m3'],
 ['嘉義', '嘉義市', 25, '2026-04-19 13:00', 'μg/m3'],
 ['臺西', '雲林縣', 15, '2026-04-19 13:00', 'μg/m3'],
 ['朴子', '嘉義縣', 23, '2026-04-19 13:00', 'μg/m3'],
 ['新港', '嘉義縣', 21, '2026-04-19 13:00', 'μg/m3'],
 ['崙背', '雲林縣', 19, '2026-04-19 13:00', 'μg/m3'],
 ['斗六', '雲林縣', 28, '2026-04-19 13:00', 'μg/m3'],
 ['南投', '南投縣', 25, '2026-04-19 13:00', 'μg/m3'],
 ['二林', '彰化縣', 20, '2026-04-19 13:00', 'μg/m3'],
 ['線西', '彰化縣', 10, '2026-04-19 13:00', 'μg/m3'],
 ['彰化', '彰化縣', 16, '2026-04-19 13:00', 'μg/m3'],
 ['西屯', '臺中市', 14, '2026-04-19 13:00', 'μg/m3'],
 ['忠明', '臺中市', 19, '2026-04-19 13:00', 'μg/m3'],
 ['大里', '臺中市', 22, '2026-04-19 13:00', 'μg/m3'],
 ['沙鹿', '臺中市', 12, '2026-04-19 13:00', 'μg/m3'],
 ['豐原', '臺中市', 16, '2026-04-19 13:00', 'μg/m3'],
 ['三義', '苗栗縣', 14, '2026-04-19 13:00', 'μg/m3'],
 ['苗栗', '苗栗縣', 10, '2026-04-19 13:00', 'μg/m3'],
 ['頭份', '苗栗縣', 15, '2026-04-19 13:00', 'μg/m3'],
 ['新竹', '新竹市', 11, '2026-04-19 13:00', 'μg/m3'],
 ['竹東', '新竹縣', 17, '2026-04-19 13:00', 'μg/m3'],
 ['湖口', '新竹縣', 10, '2026-04-19 13:00', 'μg/m3'],
 ['龍潭', '桃園市', 20, '2026-04-19 13:00', 'μg/m3'],
 ['平鎮', '桃園市', 11, '2026-04-19 13:00', 'μg/m3'],
 ['觀音', '桃園市', 10, '2026-04-19 13:00', 'μg/m3'],
 ['大園', '桃園市', 11, '2026-04-19 13:00', 'μg/m3'],
 ['桃園', '桃園市', 12, '2026-04-19 13:00', 'μg/m3'],
 ['大同', '臺北市', 20, '2026-04-19 13:00', 'μg/m3'],
 ['松山', '臺北市', 17, '2026-04-19 13:00', 'μg/m3'],
 ['古亭', '臺北市', 12, '2026-04-19 13:00', 'μg/m3'],
 ['萬華', '臺北市', 18, '2026-04-19 13:00', 'μg/m3'],
 ['中山', '臺北市', 18, '2026-04-19 13:00', 'μg/m3'],
 ['淡水', '新北市', 12, '2026-04-19 13:00', 'μg/m3'],
 ['林口', '新北市', 14, '2026-04-19 13:00', 'μg/m3'],
 ['菜寮', '新北市', 14, '2026-04-19 13:00', 'μg/m3'],
 ['新莊', '新北市', 15, '2026-04-19 13:00', 'μg/m3'],
 ['板橋', '新北市', 17, '2026-04-19 13:00', 'μg/m3'],
 ['土城', '新北市', 19, '2026-04-19 13:00', 'μg/m3'],
 ['新店', '新北市', 18, '2026-04-19 13:00', 'μg/m3'],
 ['汐止', '新北市', 19, '2026-04-19 13:00', 'μg/m3'],
 ['基隆', '基隆市', 7, '2026-04-19 13:00', 'μg/m3'],
 ['林森', '臺南市', 13, '2026-04-19 12:00', 'μg/m3'],
 ['員林', '彰化縣', 18, '2026-04-19 12:00', 'μg/m3'],
 ['臺灣大道', '臺中市', 16, '2026-04-19 12:00', 'μg/m3'],
 ['大城', '彰化縣', 18, '2026-04-19 12:00', 'μg/m3'],
 ['富貴角', '新北市', 10, '2026-04-19 12:00', 'μg/m3'],
 ['麥寮', '雲林縣', 17, '2026-04-19 12:00', 'μg/m3'],
 ['關山', '臺東縣', 12, '2026-04-19 12:00', 'μg/m3'],
 ['馬公', '澎湖縣', 18, '2026-04-19 12:00', 'μg/m3'],
 ['金門', '金門縣', 21, '2026-04-19 12:00', 'μg/m3'],
 ['馬祖', '連江縣', 21, '2026-04-19 12:00', 'μg/m3'],
 ['埔里', '南投縣', 16, '2026-04-19 12:00', 'μg/m3'],
 ['復興', '高雄市', 21, '2026-04-19 12:00', 'μg/m3'],
 ['永和', '新北市', 17, '2026-04-19 12:00', 'μg/m3'],
 ['竹山', '南投縣', 35, '2026-04-19 12:00', 'μg/m3'],
 ['中壢', '桃園市', 17, '2026-04-19 12:00', 'μg/m3'],
 ['三重', '新北市', 13, '2026-04-19 12:00', 'μg/m3'],
 ['冬山', '宜蘭縣', 13, '2026-04-19 12:00', 'μg/m3'],
 ['宜蘭', '宜蘭縣', 10, '2026-04-19 12:00', 'μg/m3'],
 ['陽明', '臺北市', 16, '2026-04-19 12:00', 'μg/m3'],
 ['花蓮', '花蓮縣', 12, '2026-04-19 12:00', 'μg/m3'],
 ['臺東', '臺東縣', 17, '2026-04-19 12:00', 'μg/m3'],
 ['恆春', '屏東縣', 17, '2026-04-19 12:00', 'μg/m3'],
 ['潮州', '屏東縣', 23, '2026-04-19 12:00', 'μg/m3'],
 ['屏東', '屏東縣', 22, '2026-04-19 12:00', 'μg/m3'],
 ['小港', '高雄市', 33, '2026-04-19 12:00', 'μg/m3'],
 ['前鎮', '高雄市', 23, '2026-04-19 12:00', 'μg/m3'],
 ['前金', '高雄市', 23, '2026-04-19 12:00', 'μg/m3'],
 ['左營', '高雄市', 23, '2026-04-19 12:00', 'μg/m3'],
 ['楠梓', '高雄市', 22, '2026-04-19 12:00', 'μg/m3'],
 ['林園', '高雄市', 30, '2026-04-19 12:00', 'μg/m3'],
 ['大寮', '高雄市', 23, '2026-04-19 12:00', 'μg/m3'],
 ['鳳山', '高雄市', 21, '2026-04-19 12:00', 'μg/m3'],
 ['仁武', '高雄市', 22, '2026-04-19 12:00', 'μg/m3'],
 ['橋頭', '高雄市', 21, '2026-04-19 12:00', 'μg/m3'],
 ['美濃', '高雄市', 17, '2026-04-19 12:00', 'μg/m3'],
 ['臺南', '臺南市', 21, '2026-04-19 12:00', 'μg/m3'],
 ['安南', '臺南市', 21, '2026-04-19 12:00', 'μg/m3'],
 ['善化', '臺南市', 20, '2026-04-19 12:00', 'μg/m3'],
 ['新營', '臺南市', 23, '2026-04-19 12:00', 'μg/m3'],
 ['嘉義', '嘉義市', 22, '2026-04-19 12:00', 'μg/m3'],
 ['臺西', '雲林縣', 12, '2026-04-19 12:00', 'μg/m3'],
 ['朴子', '嘉義縣', 24, '2026-04-19 12:00', 'μg/m3'],
 ['新港', '嘉義縣', 24, '2026-04-19 12:00', 'μg/m3'],
 ['崙背', '雲林縣', 18, '2026-04-19 12:00', 'μg/m3'],
 ['斗六', '雲林縣', 31, '2026-04-19 12:00', 'μg/m3'],
 ['南投', '南投縣', 26, '2026-04-19 12:00', 'μg/m3'],
 ['二林', '彰化縣', 18, '2026-04-19 12:00', 'μg/m3'],
 ['線西', '彰化縣', 13, '2026-04-19 12:00', 'μg/m3'],
 ['彰化', '彰化縣', 19, '2026-04-19 12:00', 'μg/m3'],
 ['西屯', '臺中市', 16, '2026-04-19 12:00', 'μg/m3'],
 ['忠明', '臺中市', 14, '2026-04-19 12:00', 'μg/m3'],
 ['大里', '臺中市', 21, '2026-04-19 12:00', 'μg/m3'],
 ['沙鹿', '臺中市', 13, '2026-04-19 12:00', 'μg/m3'],
 ['豐原', '臺中市', 16, '2026-04-19 12:00', 'μg/m3'],
 ['三義', '苗栗縣', 14, '2026-04-19 12:00', 'μg/m3'],
 ['苗栗', '苗栗縣', 20, '2026-04-19 12:00', 'μg/m3'],
 ['頭份', '苗栗縣', 11, '2026-04-19 12:00', 'μg/m3'],
 ['新竹', '新竹市', 10, '2026-04-19 12:00', 'μg/m3'],
 ['竹東', '新竹縣', 15, '2026-04-19 12:00', 'μg/m3'],
 ['湖口', '新竹縣', 13, '2026-04-19 12:00', 'μg/m3'],
 ['龍潭', '桃園市', 18, '2026-04-19 12:00', 'μg/m3'],
 ['平鎮', '桃園市', 10, '2026-04-19 12:00', 'μg/m3'],
 ['觀音', '桃園市', 6, '2026-04-19 12:00', 'μg/m3'],
 ['大園', '桃園市', 9, '2026-04-19 12:00', 'μg/m3'],
 ['桃園', '桃園市', 13, '2026-04-19 12:00', 'μg/m3'],
 ['大同', '臺北市', 15, '2026-04-19 12:00', 'μg/m3'],
 ['松山', '臺北市', 13, '2026-04-19 12:00', 'μg/m3'],
 ['古亭', '臺北市', 13, '2026-04-19 12:00', 'μg/m3'],
 ['萬華', '臺北市', 17, '2026-04-19 12:00', 'μg/m3'],
 ['中山', '臺北市', 17, '2026-04-19 12:00', 'μg/m3'],
 ['淡水', '新北市', 10, '2026-04-19 12:00', 'μg/m3'],
 ['林口', '新北市', 12, '2026-04-19 12:00', 'μg/m3'],
 ['菜寮', '新北市', 12, '2026-04-19 12:00', 'μg/m3'],
 ['新莊', '新北市', 14, '2026-04-19 12:00', 'μg/m3'],
 ['板橋', '新北市', 15, '2026-04-19 12:00', 'μg/m3'],
 ['土城', '新北市', 14, '2026-04-19 12:00', 'μg/m3'],
 ['新店', '新北市', 15, '2026-04-19 12:00', 'μg/m3'],
 ['汐止', '新北市', 17, '2026-04-19 12:00', 'μg/m3'],
 ['基隆', '基隆市', 5, '2026-04-19 12:00', 'μg/m3'],
 ['林森', '臺南市', 21, '2026-04-19 11:00', 'μg/m3'],
 ['員林', '彰化縣', 25, '2026-04-19 11:00', 'μg/m3'],
 ['臺灣大道', '臺中市', 21, '2026-04-19 11:00', 'μg/m3'],
 ['大城', '彰化縣', 17, '2026-04-19 11:00', 'μg/m3'],
 ['富貴角', '新北市', 14, '2026-04-19 11:00', 'μg/m3'],
 ['麥寮', '雲林縣', 15, '2026-04-19 11:00', 'μg/m3'],
 ['關山', '臺東縣', 15, '2026-04-19 11:00', 'μg/m3'],
 ['馬公', '澎湖縣', 18, '2026-04-19 11:00', 'μg/m3'],
 ['金門', '金門縣', 19, '2026-04-19 11:00', 'μg/m3'],
 ['馬祖', '連江縣', 25, '2026-04-19 11:00', 'μg/m3'],
 ['埔里', '南投縣', 22, '2026-04-19 11:00', 'μg/m3'],
 ['復興', '高雄市', 29, '2026-04-19 11:00', 'μg/m3'],
 ['永和', '新北市', 12, '2026-04-19 11:00', 'μg/m3'],
 ['竹山', '南投縣', 32, '2026-04-19 11:00', 'μg/m3'],
 ['中壢', '桃園市', 17, '2026-04-19 11:00', 'μg/m3'],
 ['三重', '新北市', 11, '2026-04-19 11:00', 'μg/m3'],
 ['冬山', '宜蘭縣', 10, '2026-04-19 11:00', 'μg/m3'],
 ['宜蘭', '宜蘭縣', 11, '2026-04-19 11:00', 'μg/m3'],
 ['陽明', '臺北市', 22, '2026-04-19 11:00', 'μg/m3'],
 ['花蓮', '花蓮縣', 17, '2026-04-19 11:00', 'μg/m3'],
 ['臺東', '臺東縣', 14, '2026-04-19 11:00', 'μg/m3'],
 ['恆春', '屏東縣', 13, '2026-04-19 11:00', 'μg/m3'],
 ['潮州', '屏東縣', 31, '2026-04-19 11:00', 'μg/m3'],
 ['屏東', '屏東縣', 22, '2026-04-19 11:00', 'μg/m3'],
 ['小港', '高雄市', 34, '2026-04-19 11:00', 'μg/m3'],
 ['前鎮', '高雄市', 25, '2026-04-19 11:00', 'μg/m3'],
 ['前金', '高雄市', 25, '2026-04-19 11:00', 'μg/m3'],
 ['左營', '高雄市', 23, '2026-04-19 11:00', 'μg/m3'],
 ['楠梓', '高雄市', 23, '2026-04-19 11:00', 'μg/m3'],
 ['林園', '高雄市', 32, '2026-04-19 11:00', 'μg/m3'],
 ['大寮', '高雄市', 32, '2026-04-19 11:00', 'μg/m3'],
 ['鳳山', '高雄市', 19, '2026-04-19 11:00', 'μg/m3'],
 ['仁武', '高雄市', 24, '2026-04-19 11:00', 'μg/m3'],
 ['橋頭', '高雄市', 27, '2026-04-19 11:00', 'μg/m3'],
 ['美濃', '高雄市', 24, '2026-04-19 11:00', 'μg/m3'],
 ['臺南', '臺南市', 18, '2026-04-19 11:00', 'μg/m3'],
 ['安南', '臺南市', 20, '2026-04-19 11:00', 'μg/m3'],
 ['善化', '臺南市', 22, '2026-04-19 11:00', 'μg/m3'],
 ['新營', '臺南市', 18, '2026-04-19 11:00', 'μg/m3'],
 ['嘉義', '嘉義市', 22, '2026-04-19 11:00', 'μg/m3'],
 ['臺西', '雲林縣', 16, '2026-04-19 11:00', 'μg/m3'],
 ['朴子', '嘉義縣', 23, '2026-04-19 11:00', 'μg/m3'],
 ['新港', '嘉義縣', 25, '2026-04-19 11:00', 'μg/m3'],
 ['崙背', '雲林縣', 22, '2026-04-19 11:00', 'μg/m3'],
 ['斗六', '雲林縣', 36, '2026-04-19 11:00', 'μg/m3'],
 ['南投', '南投縣', 25, '2026-04-19 11:00', 'μg/m3'],
 ['二林', '彰化縣', 22, '2026-04-19 11:00', 'μg/m3'],
 ['線西', '彰化縣', 12, '2026-04-19 11:00', 'μg/m3'],
 ['彰化', '彰化縣', 16, '2026-04-19 11:00', 'μg/m3'],
 ['西屯', '臺中市', 15, '2026-04-19 11:00', 'μg/m3'],
 ['忠明', '臺中市', 17, '2026-04-19 11:00', 'μg/m3'],
 ['大里', '臺中市', 25, '2026-04-19 11:00', 'μg/m3'],
 ['沙鹿', '臺中市', 14, '2026-04-19 11:00', 'μg/m3'],
 ['豐原', '臺中市', 18, '2026-04-19 11:00', 'μg/m3'],
 ['三義', '苗栗縣', 20, '2026-04-19 11:00', 'μg/m3'],
 ['苗栗', '苗栗縣', 14, '2026-04-19 11:00', 'μg/m3'],
 ['頭份', '苗栗縣', 13, '2026-04-19 11:00', 'μg/m3'],
 ['新竹', '新竹市', 18, '2026-04-19 11:00', 'μg/m3'],
 ['竹東', '新竹縣', 12, '2026-04-19 11:00', 'μg/m3'],
 ['湖口', '新竹縣', 11, '2026-04-19 11:00', 'μg/m3'],
 ['龍潭', '桃園市', 15, '2026-04-19 11:00', 'μg/m3'],
 ['平鎮', '桃園市', 11, '2026-04-19 11:00', 'μg/m3'],
 ['觀音', '桃園市', 7, '2026-04-19 11:00', 'μg/m3'],
 ['大園', '桃園市', 6, '2026-04-19 11:00', 'μg/m3'],
 ['桃園', '桃園市', 15, '2026-04-19 11:00', 'μg/m3'],
 ['大同', '臺北市', 11, '2026-04-19 11:00', 'μg/m3'],
 ['松山', '臺北市', 10, '2026-04-19 11:00', 'μg/m3'],
 ['古亭', '臺北市', 9, '2026-04-19 11:00', 'μg/m3'],
 ['萬華', '臺北市', 16, '2026-04-19 11:00', 'μg/m3'],
 ['中山', '臺北市', 11, '2026-04-19 11:00', 'μg/m3'],
 ['淡水', '新北市', 12, '2026-04-19 11:00', 'μg/m3'],
 ['林口', '新北市', 11, '2026-04-19 11:00', 'μg/m3'],
 ['菜寮', '新北市', 17, '2026-04-19 11:00', 'μg/m3'],
 ['新莊', '新北市', 11, '2026-04-19 11:00', 'μg/m3'],
 ['板橋', '新北市', 13, '2026-04-19 11:00', 'μg/m3'],
 ['土城', '新北市', 11, '2026-04-19 11:00', 'μg/m3'],
 ['新店', '新北市', 14, '2026-04-19 11:00', 'μg/m3'],
 ['汐止', '新北市', 13, '2026-04-19 11:00', 'μg/m3'],
 ['基隆', '基隆市', 9, '2026-04-19 11:00', 'μg/m3'],
 ['林森', '臺南市', 23, '2026-04-19 10:00', 'μg/m3'],
 ['員林', '彰化縣', 25, '2026-04-19 10:00', 'μg/m3'],
 ['臺灣大道', '臺中市', 23, '2026-04-19 10:00', 'μg/m3'],
 ['大城', '彰化縣', 19, '2026-04-19 10:00', 'μg/m3'],
 ['富貴角', '新北市', 8, '2026-04-19 10:00', 'μg/m3'],
 ['麥寮', '雲林縣', 21, '2026-04-19 10:00', 'μg/m3'],
 ['關山', '臺東縣', 20, '2026-04-19 10:00', 'μg/m3'],
 ['馬公', '澎湖縣', 26, '2026-04-19 10:00', 'μg/m3'],
 ['金門', '金門縣', 30, '2026-04-19 10:00', 'μg/m3'],
 ['馬祖', '連江縣', 23, '2026-04-19 10:00', 'μg/m3'],
 ['埔里', '南投縣', 29, '2026-04-19 10:00', 'μg/m3'],
 ['復興', '高雄市', 31, '2026-04-19 10:00', 'μg/m3'],
 ['永和', '新北市', 13, '2026-04-19 10:00', 'μg/m3'],
 ['竹山', '南投縣', 29, '2026-04-19 10:00', 'μg/m3'],
 ['中壢', '桃園市', 15, '2026-04-19 10:00', 'μg/m3'],
 ['三重', '新北市', 15, '2026-04-19 10:00', 'μg/m3'],
 ['冬山', '宜蘭縣', 13, '2026-04-19 10:00', 'μg/m3'],
 ['宜蘭', '宜蘭縣', 15, '2026-04-19 10:00', 'μg/m3'],
 ['陽明', '臺北市', 15, '2026-04-19 10:00', 'μg/m3'],
 ['花蓮', '花蓮縣', 15, '2026-04-19 10:00', 'μg/m3'],
 ['臺東', '臺東縣', 19, '2026-04-19 10:00', 'μg/m3'],
 ['恆春', '屏東縣', 11, '2026-04-19 10:00', 'μg/m3'],
 ['潮州', '屏東縣', 29, '2026-04-19 10:00', 'μg/m3'],
 ['屏東', '屏東縣', 28, '2026-04-19 10:00', 'μg/m3'],
 ['小港', '高雄市', 40, '2026-04-19 10:00', 'μg/m3'],
 ['前鎮', '高雄市', 28, '2026-04-19 10:00', 'μg/m3'],
 ['前金', '高雄市', 29, '2026-04-19 10:00', 'μg/m3'],
 ['左營', '高雄市', 33, '2026-04-19 10:00', 'μg/m3'],
 ['楠梓', '高雄市', 28, '2026-04-19 10:00', 'μg/m3'],
 ['林園', '高雄市', 31, '2026-04-19 10:00', 'μg/m3'],
 ['大寮', '高雄市', 36, '2026-04-19 10:00', 'μg/m3'],
 ['鳳山', '高雄市', 28, '2026-04-19 10:00', 'μg/m3'],
 ['仁武', '高雄市', 29, '2026-04-19 10:00', 'μg/m3'],
 ['橋頭', '高雄市', 31, '2026-04-19 10:00', 'μg/m3'],
 ['美濃', '高雄市', 22, '2026-04-19 10:00', 'μg/m3'],
 ['臺南', '臺南市', 21, '2026-04-19 10:00', 'μg/m3'],
 ['安南', '臺南市', 22, '2026-04-19 10:00', 'μg/m3'],
 ['善化', '臺南市', 24, '2026-04-19 10:00', 'μg/m3'],
 ['新營', '臺南市', 15, '2026-04-19 10:00', 'μg/m3'],
 ['嘉義', '嘉義市', 25, '2026-04-19 10:00', 'μg/m3'],
 ['臺西', '雲林縣', 19, '2026-04-19 10:00', 'μg/m3'],
 ['朴子', '嘉義縣', 23, '2026-04-19 10:00', 'μg/m3'],
 ['新港', '嘉義縣', 19, '2026-04-19 10:00', 'μg/m3'],
 ['崙背', '雲林縣', 25, '2026-04-19 10:00', 'μg/m3'],
 ['斗六', '雲林縣', 38, '2026-04-19 10:00', 'μg/m3'],
 ['南投', '南投縣', 31, '2026-04-19 10:00', 'μg/m3'],
 ['二林', '彰化縣', 29, '2026-04-19 10:00', 'μg/m3'],
 ['線西', '彰化縣', 21, '2026-04-19 10:00', 'μg/m3'],
 ['彰化', '彰化縣', 22, '2026-04-19 10:00', 'μg/m3'],
 ['西屯', '臺中市', 16, '2026-04-19 10:00', 'μg/m3'],
 ['忠明', '臺中市', 23, '2026-04-19 10:00', 'μg/m3'],
 ['大里', '臺中市', 29, '2026-04-19 10:00', 'μg/m3'],
 ['沙鹿', '臺中市', 14, '2026-04-19 10:00', 'μg/m3'],
 ['豐原', '臺中市', 19, '2026-04-19 10:00', 'μg/m3'],
 ['三義', '苗栗縣', 10, '2026-04-19 10:00', 'μg/m3'],
 ['苗栗', '苗栗縣', 16, '2026-04-19 10:00', 'μg/m3'],
 ['頭份', '苗栗縣', 16, '2026-04-19 10:00', 'μg/m3'],
 ['新竹', '新竹市', 10, '2026-04-19 10:00', 'μg/m3'],
 ['竹東', '新竹縣', 13, '2026-04-19 10:00', 'μg/m3'],
 ['湖口', '新竹縣', 16, '2026-04-19 10:00', 'μg/m3'],
 ['龍潭', '桃園市', 15, '2026-04-19 10:00', 'μg/m3'],
 ['平鎮', '桃園市', 11, '2026-04-19 10:00', 'μg/m3'],
 ['觀音', '桃園市', 8, '2026-04-19 10:00', 'μg/m3'],
 ['大園', '桃園市', 16, '2026-04-19 10:00', 'μg/m3'],
 ['桃園', '桃園市', 13, '2026-04-19 10:00', 'μg/m3'],
 ['大同', '臺北市', 5, '2026-04-19 10:00', 'μg/m3'],
 ['松山', '臺北市', 12, '2026-04-19 10:00', 'μg/m3'],
 ['古亭', '臺北市', 14, '2026-04-19 10:00', 'μg/m3'],
 ['萬華', '臺北市', 0, '2026-04-19 10:00', 'μg/m3'],
 ['中山', '臺北市', 15, '2026-04-19 10:00', 'μg/m3'],
 ['淡水', '新北市', 10, '2026-04-19 10:00', 'μg/m3'],
 ['林口', '新北市', 11, '2026-04-19 10:00', 'μg/m3'],
 ['菜寮', '新北市', 14, '2026-04-19 10:00', 'μg/m3'],
 ['新莊', '新北市', 11, '2026-04-19 10:00', 'μg/m3'],
 ['板橋', '新北市', 13, '2026-04-19 10:00', 'μg/m3'],
 ['土城', '新北市', 12, '2026-04-19 10:00', 'μg/m3'],
 ['新店', '新北市', 13, '2026-04-19 10:00', 'μg/m3'],
 ['汐止', '新北市', 14, '2026-04-19 10:00', 'μg/m3'],
 ['基隆', '基隆市', 11, '2026-04-19 10:00', 'μg/m3'],
 ['林森', '臺南市', 30, '2026-04-19 09:00', 'μg/m3'],
 ['員林', '彰化縣', 32, '2026-04-19 09:00', 'μg/m3'],
 ['臺灣大道', '臺中市', 23, '2026-04-19 09:00', 'μg/m3'],
 ['大城', '彰化縣', 27, '2026-04-19 09:00', 'μg/m3'],
 ['富貴角', '新北市', 10, '2026-04-19 09:00', 'μg/m3'],
 ['麥寮', '雲林縣', 21, '2026-04-19 09:00', 'μg/m3'],
 ['關山', '臺東縣', 22, '2026-04-19 09:00', 'μg/m3'],
 ['馬公', '澎湖縣', 22, '2026-04-19 09:00', 'μg/m3'],
 ['金門', '金門縣', 22, '2026-04-19 09:00', 'μg/m3'],
 ['馬祖', '連江縣', 19, '2026-04-19 09:00', 'μg/m3'],
 ['埔里', '南投縣', 31, '2026-04-19 09:00', 'μg/m3'],
 ['復興', '高雄市', 39, '2026-04-19 09:00', 'μg/m3'],
 ['永和', '新北市', 15, '2026-04-19 09:00', 'μg/m3'],
 ['竹山', '南投縣', 38, '2026-04-19 09:00', 'μg/m3'],
 ['中壢', '桃園市', 19, '2026-04-19 09:00', 'μg/m3'],
 ['三重', '新北市', 17, '2026-04-19 09:00', 'μg/m3'],
 ['冬山', '宜蘭縣', 10, '2026-04-19 09:00', 'μg/m3'],
 ['宜蘭', '宜蘭縣', 8, '2026-04-19 09:00', 'μg/m3'],
 ['陽明', '臺北市', 11, '2026-04-19 09:00', 'μg/m3'],
 ['花蓮', '花蓮縣', 18, '2026-04-19 09:00', 'μg/m3'],
 ['臺東', '臺東縣', 18, '2026-04-19 09:00', 'μg/m3'],
 ['恆春', '屏東縣', 13, '2026-04-19 09:00', 'μg/m3'],
 ['潮州', '屏東縣', 33, '2026-04-19 09:00', 'μg/m3'],
 ['屏東', '屏東縣', 34, '2026-04-19 09:00', 'μg/m3'],
 ['小港', '高雄市', 40, '2026-04-19 09:00', 'μg/m3'],
 ['前鎮', '高雄市', 36, '2026-04-19 09:00', 'μg/m3'],
 ['前金', '高雄市', 25, '2026-04-19 09:00', 'μg/m3'],
 ['左營', '高雄市', 30, '2026-04-19 09:00', 'μg/m3'],
 ['楠梓', '高雄市', 34, '2026-04-19 09:00', 'μg/m3'],
 ['林園', '高雄市', 36, '2026-04-19 09:00', 'μg/m3'],
 ['大寮', '高雄市', 42, '2026-04-19 09:00', 'μg/m3'],
 ['鳳山', '高雄市', 37, '2026-04-19 09:00', 'μg/m3'],
 ['仁武', '高雄市', 35, '2026-04-19 09:00', 'μg/m3'],
 ['橋頭', '高雄市', 29, '2026-04-19 09:00', 'μg/m3'],
 ['美濃', '高雄市', 28, '2026-04-19 09:00', 'μg/m3'],
 ['臺南', '臺南市', 31, '2026-04-19 09:00', 'μg/m3'],
 ['安南', '臺南市', 30, '2026-04-19 09:00', 'μg/m3'],
 ['善化', '臺南市', 19, '2026-04-19 09:00', 'μg/m3'],
 ['新營', '臺南市', 23, '2026-04-19 09:00', 'μg/m3'],
 ['嘉義', '嘉義市', 35, '2026-04-19 09:00', 'μg/m3'],
 ['臺西', '雲林縣', 6, '2026-04-19 09:00', 'μg/m3'],
 ['朴子', '嘉義縣', 21, '2026-04-19 09:00', 'μg/m3'],
 ['新港', '嘉義縣', 32, '2026-04-19 09:00', 'μg/m3'],
 ['崙背', '雲林縣', 30, '2026-04-19 09:00', 'μg/m3'],
 ['斗六', '雲林縣', 35, '2026-04-19 09:00', 'μg/m3'],
 ['南投', '南投縣', 36, '2026-04-19 09:00', 'μg/m3'],
 ['二林', '彰化縣', 28, '2026-04-19 09:00', 'μg/m3'],
 ['線西', '彰化縣', 16, '2026-04-19 09:00', 'μg/m3'],
 ['彰化', '彰化縣', 27, '2026-04-19 09:00', 'μg/m3'],
 ['西屯', '臺中市', 16, '2026-04-19 09:00', 'μg/m3'],
 ['忠明', '臺中市', 21, '2026-04-19 09:00', 'μg/m3'],
 ['大里', '臺中市', 28, '2026-04-19 09:00', 'μg/m3'],
 ['沙鹿', '臺中市', 19, '2026-04-19 09:00', 'μg/m3'],
 ['豐原', '臺中市', 17, '2026-04-19 09:00', 'μg/m3'],
 ['三義', '苗栗縣', 14, '2026-04-19 09:00', 'μg/m3'],
 ['苗栗', '苗栗縣', 17, '2026-04-19 09:00', 'μg/m3'],
 ['頭份', '苗栗縣', 11, '2026-04-19 09:00', 'μg/m3'],
 ['新竹', '新竹市', 13, '2026-04-19 09:00', 'μg/m3'],
 ['竹東', '新竹縣', 19, '2026-04-19 09:00', 'μg/m3'],
 ['湖口', '新竹縣', 14, '2026-04-19 09:00', 'μg/m3'],
 ['龍潭', '桃園市', 16, '2026-04-19 09:00', 'μg/m3'],
 ['平鎮', '桃園市', 13, '2026-04-19 09:00', 'μg/m3'],
 ['觀音', '桃園市', 15, '2026-04-19 09:00', 'μg/m3'],
 ['大園', '桃園市', 17, '2026-04-19 09:00', 'μg/m3'],
 ['桃園', '桃園市', 11, '2026-04-19 09:00', 'μg/m3'],
 ['大同', '臺北市', 17, '2026-04-19 09:00', 'μg/m3'],
 ['松山', '臺北市', 9, '2026-04-19 09:00', 'μg/m3'],
 ['古亭', '臺北市', 15, '2026-04-19 09:00', 'μg/m3'],
 ['萬華', '臺北市', 20, '2026-04-19 09:00', 'μg/m3'],
 ['中山', '臺北市', 16, '2026-04-19 09:00', 'μg/m3'],
 ['淡水', '新北市', 12, '2026-04-19 09:00', 'μg/m3'],
 ['林口', '新北市', 10, '2026-04-19 09:00', 'μg/m3'],
 ['菜寮', '新北市', 15, '2026-04-19 09:00', 'μg/m3'],
 ['新莊', '新北市', 13, '2026-04-19 09:00', 'μg/m3'],
 ['板橋', '新北市', 13, '2026-04-19 09:00', 'μg/m3'],
 ['土城', '新北市', 11, '2026-04-19 09:00', 'μg/m3'],
 ['新店', '新北市', 15, '2026-04-19 09:00', 'μg/m3'],
 ['汐止', '新北市', 15, '2026-04-19 09:00', 'μg/m3'],
 ['基隆', '基隆市', 12, '2026-04-19 09:00', 'μg/m3'],
 ['林森', '臺南市', 32, '2026-04-19 08:00', 'μg/m3'],
 ['員林', '彰化縣', 28, '2026-04-19 08:00', 'μg/m3'],
 ['臺灣大道', '臺中市', 25, '2026-04-19 08:00', 'μg/m3'],
 ['大城', '彰化縣', 21, '2026-04-19 08:00', 'μg/m3'],
 ['富貴角', '新北市', 11, '2026-04-19 08:00', 'μg/m3'],
 ['麥寮', '雲林縣', 26, '2026-04-19 08:00', 'μg/m3'],
 ['關山', '臺東縣', 21, '2026-04-19 08:00', 'μg/m3'],
 ['馬公', '澎湖縣', 21, '2026-04-19 08:00', 'μg/m3'],
 ['金門', '金門縣', 29, '2026-04-19 08:00', 'μg/m3'],
 ['馬祖', '連江縣', 31, '2026-04-19 08:00', 'μg/m3'],
 ['埔里', '南投縣', 29, '2026-04-19 08:00', 'μg/m3'],
 ['復興', '高雄市', 35, '2026-04-19 08:00', 'μg/m3'],
 ['永和', '新北市', 18, '2026-04-19 08:00', 'μg/m3'],

https://inloop.github.io/sqlite-viewer/

In [16]:
# 插入多筆 .executemany
cursor.executemany(sqlstr, df1.values.tolist())
conn.commit()

In [17]:
# cursor.rowcount 查看更新幾筆資料
cursor.rowcount

0

In [18]:
conn.close()